####################################################
#
# Welcome to Tokyo Jekyll Theme
# Author Link : https://themeix.com/
# Version : v1.0.2
#
####################################################

# Site settings
title: "Byeongho Yu"
email: "bhyu@kaist.ac.kr"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://bhyu0924.github.io # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/img/logo_dog.jpg
description: "연구일지"
keywords: "Robotics, VIO, SLAM, UAV, Quadrupedal robot"
# mailchimp: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=4784863884"
# facebook: https://facebook.com/themeix
instagram: https://www.instagram.com/bhyu.93
# twitter: https://twitter.com/themeix_com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  authors:
    output: true
    permalink: /author/:path/

feed:
  collections:
    posts:
      path: "/index.xml"
